### ISSUE TITLE
columnfamiles with list entries are exported as null

### ISSUE THREAD

**Issue by pmpronan** [brianmhess/cassandra-loader#10]
i have a columnfamily as such:
userid text PRIMARY KEY,
    blackouts list<text>,
    calendars list<text>,
    country text,
    devices list<text>,
    general_health text,
    industry text,
    job text,
    privacy boolean,
    status text

exports always result in blackouts, calendars and devices being null.
export file below:
18222080-51e6-464e-a23c-9ed4f16c88a1,null,null,England,null,good,Banking,manager,FALSE,active
65b469d3-2156-4749-9b2a-4741244d5301,null,null,Germany,null,good,Retail,Barber,TRUE,active
61debe56-95f7-4023-b3b7-747d8c6050d7,null,null,France,null,poor,Healthcare,programmer,TRUE,active
d1a8f0e6-3a6b-4d2f-8763-9c468053b68a,null,null,Italy,null,good,Farming,Bee Keeper,FALSE,active

command used for export:
cassandra-unloader -numThreads 1 -f profile.data -host 127.0.0.1 -schema "dev.profile(userid,blackouts,calendars,country,devices,general_health,industry,job,privacy,status)"

**Comment by brianmhess** [comment]
Which version of cassandra-unloader did you use? You can tell by calling cassandra-unloader with no arguments. It's printed at the top of the usage statement.  
Collections weren't supported in cassandra-unloader until v0.0.14

**Comment by pmpronan** [comment]
Brian,
 thanks, i was using .12 - have taken .14 and collections are appearing.

thanks for the response.
Paul.
