### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by jcross-linkup** [brianmhess/cassandra-loader#100]
Just saw this a bit ago:
https://www.datastax.com/2018/05/introducing-datastax-bulk-loader

In addition, there haven't been any commits in over a year, and pull requests aren't being accepted, rejected, or discussed.

Based on those things I'm wondering: Are there are any plans to continue this project?

**Comment by brianmhess** [comment]
There aren't a lot of plans to do any active development, no.
