### ISSUE TITLE
missing repos

### ISSUE THREAD

**Issue by k1ng87** [brianmhess/cassandra-loader#12]
My linux env doesn't have access to certain sites to get the repos...can you include them in the build?

* What went wrong:
A problem occurred evaluating root project 'bulkload'.
> Could not resolve all dependencies for configuration ':runtime'.
   > Could not resolve com.datastax.cassandra:cassandra-driver-core:2.1.6.
     Required by:
         :bulkload:unspecified
      > Could not GET 'https://repo1.maven.org/maven2/com/datastax/cassandra/cassandra-driver-core/2.1.6/cassandra-driver-core-2.1.6.pom'.
         > Connection to https://repo1.maven.org refused
   > Could not resolve org.xerial.snappy:snappy-java:1.0.5.
     Required by:
         :bulkload:unspecified
      > Could not GET 'https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.0.5/snappy-java-1.0.5.pom'.
         > Connection to https://repo1.maven.org refused
   > Could not resolve net.jpountz.lz4:lz4:1.2.0.
     Required by:
         :bulkload:unspecified
      > Could not GET 'https://repo1.maven.org/maven2/net/jpountz/lz4/lz4/1.2.0/lz4-1.2.0.pom'.
         > Connection to https://repo1.maven.org refused

**Comment by brianmhess** [comment]
I'm resistant to doing that.  I think the more appropriate approach is to fix the maven/gradle/build environment to address these dependencies.
