### ISSUE TITLE
Cassandra Collection is not loaded correctly

### ISSUE THREAD

**Issue by xqchen1** [brianmhess/cassandra-loader#14]
Hi Brian,

I mentioned the issue with loading collections after your presentation at Cassandra Summit last week.  This is a great tool and hope you can enhance collections loading. The records were loaded but the collection data was not loaded correctly - please see the csv file and loaded cqlsh table rows below.  

Thanks,
Jane

load_collection.csv file

[root@usddcas01 test-load]# cat load_collection.csv
23,A23323226_d_X,925077069999,1,"[1, 2]"
23,A23323226_d_X,925077069999,2,"[1, 2, 1, 2, 3, 4]"
23,A23323226_d_X,925077069999,3,"[1, 2, 1, 2, 3, 4, 1, 2, 3, 4]"

cqlsh:demo> select * from load_collection;

 p_key | sub_id | c_key | l_seq | d_seq
-----------+------------+-----------+----------+----------

cqlsh:demo> exit
# ./cassandra-loader -f load_collection.csv -host xxxx -schema "demo.load_collection(p_key,sub_id,c_key,l_seq,d_seq)"

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
*** Processing load_collection.csv
*** DONE: load_collection.csv  number of lines processed: 3 (3 inserted)
Lines Processed:        3  Rate:        0.0
#  test-load]# cqlsh
Connected to Jane Test Cluster at x.x.x.x:9042.
[cqlsh 5.0.1 | Cassandra 2.1.8.621 | DSE 4.7.2 | CQL spec 3.2.0 | Native protocol v3]
Use HELP for help.
cqlsh:demo> select * from load_collection;

 p_key     | sub_id        | c_key        | l_seq    | d_seq
-----------+---------------+--------------+----------+--------------------------------------------------------
        23 | A23323226_d_X | 925077069999 |        1 |                                                 [1, 2]
        23 | A23323226_d_X | 925077069999 |        2 |                               [1, 2, 1, 2, 1, 2, 3, 4]
        23 | A23323226_d_X | 925077069999 |        3 | [1, 2, 1, 2, 1, 2, 3, 4, 1, 2, 1, 2, 3, 4, 1, 2, 3, 4]

**Comment by brianmhess** [comment]
I see what I did (facepalm).  Fixing it in 0.0.16.
