### ISSUE TITLE
unloading a columnfamily containing blob column yields stringified HeapByteBuffer object

### ISSUE THREAD

**Issue by GooseYArd** [brianmhess/cassandra-loader#15]
When dumping a table having a blob column, I noticed that the column in the output corresponding to the blob contains values like:

"java.nio.HeapByteBuffer[pos=0 lim=6211 cap=6211]"

rather than the content of the blob. Is it possible to have the unloader include the actual blob bytes? I'm guessing I may need to invoke the tool differently, but didn't see anything obvious in the docs.

Thanks btw, this tool is a lifesaver!

**Comment by brianmhess** [comment]
How about BLOBs being Base64 encoded?  That is what I'm checking in for 0.0.16 (to be seen soon :) )

**Comment by GooseYArd** [comment]
That would be _perfect_

**Comment by brianmhess** [comment]
Try v0.0.16 :-)
