### ISSUE TITLE
Unloader writes text data with unescaped newlines

### ISSUE THREAD

**Issue by KenMcK1** [brianmhess/cassandra-loader#16]
The unloader writes text fields containing newlines without escaping them. This breaks the loader. Either newlines (and maybe some other characters like tabs) should be escaped, or there should be an option to change the line end delimiter to something that won't appear in the data.

**Comment by vitoonpto** [comment]
I agree!  I have large text fields with newlines.  I am getting linecounts from the unloader that don't agree with the record count in Cassandra.

**Comment by brianmhess** [comment]
I believe this is now fixed in v0.0.19.
