### ISSUE TITLE
Loader Quoting/Escaping and Data Corruption

### ISSUE THREAD

**Issue by rs017991** [brianmhess/cassandra-loader#22]
The loader & parsers have some pretty glaring issues with quoting/escaping that not only cause errors, but worse: can cause data to be silently corrupted.

I started to fix some of these myself, but quickly realized that the issues were architectural; It will need a bit of an overhaul to make this enterprise-ready. We might have to go a different route, but here are the results of my research if you want to take a crack at it.
## CSV

While CSV is a bit of an amorphous spec, there are some core behaviours that are arguably  necessary to implement. As it stands, you can't really run any CSV file through cassandra-loader that was written by Excel or any other mainstream CSV processing library. This should really be solved by _using_ one of those libraries, instead of writing a CSV implementation from scratch.

**Escaping Quotes**
In the case where double-quotes are present in the field text, a proper CSV writer will escape each one with another double-quote, and then double-quote the entire field. cassandra-loader does not un-escape these when reading the CSV.
For example:
Raw Text: **Text "with" Quotes**
CSV Field: **"Text ""with"" Quotes"**
cassandra-loader writes **Text ""with"" Quotes** to the database

**Preserving Whitespace**
cassandra-loader performs a 'trim' on field contents, even when quoted, causing leading and trailing whitespace to be lost. Worse, whitespace-only fields will be inserted as null with the default nullString. Really, when whitespace is within the quoted area, it should never be removed.

There is also the issue of newlines, as reported by https://github.com/brianmhess/cassandra-loader/issues/16
## Collections

These issues get much worse once we start using collections. Again, it seems like we ought to be treating these as JSON or something that can be parsed with an existing library, rather than trying to roll something new.

Note: For readability, the below examples will not include any CSV quoting.

**Text Containing Commas**
cassandra-loader chokes when commas are present in any text element of a set, list, or map.
For example, the simplest case of **{","}** will cause the following error:
`Invalid format in input 0: Must end with }`

As I was looking through the code, I noticed that there was handling for the backslash to be used as an escape character. Since it is [undocumented](https://github.com/brianmhess/cassandra-loader/blob/master/README.md), I'm not sure what the expected behaviour is, but here are my observations:
- When used to escape commas, it prevents the above error, but causes data corruption, as it carries the backslash with it. Thus, in the example above, doing **{"\,"}** will cause **\,** to be written to the database set.
- Since we're inside a set of double-quotes, we should not need to escape the comma in the first place.

**Text Containing Double-Quotes**
Similar to the previous case, an error will be thrown when unescaped quotes are present in a collection(but only if there are an odd number of them, and the collection contains further elements). The main difference here is that we _would_ expect quotes to require escaping.

As with commas, escaping with backslashes silences the error, but causes the same data corruption, as the backslashes end up in the database.

**Maps With Text Keys & Values**
When maps only have text as either key _or_ value, (i.e. **{1: "a", 2: "b"}** or **{"a": 1, "b": 2}**), then it seems to work okay.
However, if both keys _and_ values are text(i.e. **{"a": "b", "x": "y"}**), then everything becomes corrupted. In this example, the following entries will be written to the database map:
- Key: **x":"y** Value: **null**
- Key: **a":"b** Value: **null**

**Preserving Whitespace**
As with the CSV-level code, leading/trailing whitespace is lost from quoted text areas within collections(ex: **{" "}**).

**Comment by al3xandru** [comment]
@rs017991 if possible I'd appreciate if you could take a look at https://github.com/al3xandru/cassandra-loader/blob/parser/src/test/java/com/datastax/loader/parser/StringParserTest.java and double check the test covers the correct cases for strings. 

(I'll look into handling collections next)

**Comment by rs017991** [comment]
__StringParserTest__ looks good.

__CollectionParserTest__ has some good-looking __List__ Tests, but __Set__ and __Map__ still need some attention. After running some tests of my own, Maps/Sets still appear to be broken.

**Comment by brianmhess** [comment]
I think this is addressed with the move to the Univocity parser.  Can you check v0.0.21 to see if you still see issues?

**Comment by rs017991** [comment]
After running some further tests, some issues have been resolved, some not so much.

__Resolved__
- ___Preserving Whitespace___
- ___Collections: Text Containing Commas___
- ___Collections: Preserving Whitespace___

__Partially Resolved__
- ___Escaping Quotes___: This is working now, except for a few edge cases:
 - When the field value is only a single double-quote char: __"\\""__
   - Causes StringIndexOutOfBoundsException
 - When the field value starts/ends with a single double-quote char: __"\\"hello\\""__
   - Quote chars are missing in the database
- ___Collections: Text Containing Double-Quotes___: This is working now in Sets/Lists (but not in Maps, see below). Also, the two edge cases above happen in Sets/Lists too.

__Unresolved__
- ___Maps With Text Keys & Values___:
  - It looks like __MapParser__ is performing CSV-escaping, even though the text was already CSV-escaped by __DelimParser__, causing all sorts of havoc.
    - This also means that it's no longer just string/string Maps that are broken; int/string, string/int, etc are now broken as well.

**Comment by brianmhess** [comment]
So - I have a fix that I'm about to check in, but wanted to see what you think about the solution.
The escaped quotes is now working - one too many unescapes....
Collections must be enclosed in double-quotes (so that the top level delimited parser finds the individual fields and keeps the collection as a whole).  As such, fields inside the collection must be escaped.  For example, to get the map of double-quote to 123, you would do "{\"\\\"\": 123}".  When we unescape the map itself, we get {"\"": 123}, which we then parse the key "\"" and again unescape to get " for the key.
Is that sufficient?  I agree it isn't as user-friendly as I'd like, but if you want to support the colon in the key, you need to have the ability for key be quoted as "{\"abc:def\": 999}" to get abc:def to map to 999.
The maps issue was that I had transposed the roles of the : and , character in parsing the map.... havoc is putting it lightly :)
If you think this escaping "fun" is acceptable, I'll check it in. I tried not doing the escaping, but there end up being some strings you can't really express.  I think this might be the best option.

**Comment by rs017991** [comment]
Yeah, sounds good to me

**Comment by rs017991** [comment]
After the latest change, things are looking a lot better.

The only problem I'm seeing right now is commas inside Map keys/values. for example:
`"{\",\":1}"`
Surprisingly, the comma becomes a newline in the final map:
__Key: \n__
__Value: 1__

**Comment by brianmhess** [comment]
Fixed it.  Univocity was "helping" in a way I didn't expect.
