### ISSUE TITLE
Loader inserts null values

### ISSUE THREAD

**Issue by rs017991** [brianmhess/cassandra-loader#23]
The Loader prepares an insert statement with all columns and uses it on every row, regardless of whether the row has null for some(or many) of those columns.

This may cause a lot of tombstones to be created, waste a whole lot of space, and slow down the load with extra I/O.

It would be better to create/cache PreparedStatements for the various permutations of present columns as they are encountered.

**Comment by brianmhess** [comment]
I considered this approach, but the number of PreparedStatements would grow exponentially - and after a while it would seriously impact performance as only a fixed number of PreparedStatements are cached on each Cassandra node.
There is a driver improvement that will allow you to specify that missing data should be omitted (as opposed to inserting a NULL which is a tombstone).  That is coming in the 2.2 (and 3.0) version of the driver.  I will bring that in when I move to the 2.2/3.0 driver, but it would only have that behavior on clusters at version 2.2+ (it involved a server-side change, actually).
