### ISSUE TITLE
Unable to (un)load  from keyspace with a dash in its name.

### ISSUE THREAD

**Issue by mickaelgervais** [brianmhess/cassandra-loader#24]
I'm trying to (un)load data from a keyspace which has a dash ('-') in its name.

This is due to the [regex](https://github.com/brianmhess/cassandra-loader/blob/master/src/main/java/com/datastax/loader/CqlDelimParser.java#L116).

Thanks

Mickaël

**Comment by al3xandru** [comment]
According to the [spec](http://docs.datastax.com/en/cql/3.3/cql/cql_reference/ref-lexical-valid-chars.html) dashes are not allowed in the keyspace, table, column identifiers.

**Comment by brianmhess** [comment]
Dash is not allowed in a Keyspace or Table name.
