### ISSUE TITLE
How are the queries handled with threads ?

### ISSUE THREAD

**Issue by chirag93** [brianmhess/cassandra-loader#26]
Hi,  how are the queries handled at multiple threads ?  how do you split and execute them and where is this being handled ?

**Comment by brianmhess** [comment]
The level of multi-threading is done at the file level.  That is, each file is processed by one thread.  The threads work on a file and then get the next file to work on.  

The code that creates the thread pool and fills with threads is:
https://github.com/brianmhess/cassandra-loader/blob/master/src/main/java/com/datastax/loader/CqlDelimLoad.java#L562-L584
