### ISSUE TITLE
Specify a query predicate for unloader

### ISSUE THREAD

**Issue by jeromatron** [brianmhess/cassandra-loader#39]
It would be nice to specify a query predicate for the unloader, for periodic dumps of specific ranges of data.

**Comment by brianmhess** [comment]
Would you want to just specify a WHERE clause, sort of like:
-where "X = 100"
or
-where "Y = 100 ALLOW FILTERING"

**Comment by jeromatron** [comment]
Yes - something of a predicate.  Someone mentioned exporting the change from the last 24 hours which is presumably in the data itself.  So perhaps "where registered_date > '2016-05-09".

**Comment by sshcherbakov** [comment]
+1

**Comment by nitindeokate99** [comment]
Is this feature added to unloader??

**Comment by nitindeokate99** [comment]
any updates? It seems this forum in in-active :-1:

**Comment by brianmhess** [comment]
I have not added this feature yet.  I've been focused on some other areas on the loading side.  I may be able to do something like this in the (near?) future.

**Comment by jeromatron** [comment]
It should be relatively simple to add a way to specify a clause and use that in the query underneath.  PRs are welcome :) I don't know when I'll be able to get to it either right now.

**Comment by nitindeokate99** [comment]
Will wait for this feature

**Comment by brianmhess** [comment]
This has been added to v0.0.19.

**Comment by nitindeokate99** [comment]
how to use this ?
e.g cassandra-unloader -f zz -host my_machine -numThreads 1 -schema "keyspacedirectory.tbl_emp(empid, name, surname)

**Comment by brianmhess** [comment]
What are you trying to accomplish? The new argument is -where:
cassandra-unloader -f zz -host my_machine -numThreads 1 -schema "keyspacedirectory.tbl_emp(empid, name, surname)" -where "empid = 12345"

**Comment by nitindeokate99** [comment]
thanks. I was looking for syntax.
