### ISSUE TITLE
Unload into single file

### ISSUE THREAD

**Issue by nitindeokate99** [brianmhess/cassandra-loader#42]
I see when I try unloader, it creates multiple files. It uses filename given along with -f option.
Question is: Can I get all data into a single file?

**Comment by brianmhess** [comment]
Yes. Set the number of threads "-numThreads" to 1. Alternatively, you can set "-f stdout" which will put the data to STDOUT and you can redirect that to a file: cassandra-loader -f stdout ... > /path/to/file.csv

**Comment by nitindeokate99** [comment]
cool thanks
