### ISSUE TITLE
Quoted data  has padded with extra “

### ISSUE THREAD

**Issue by santhikumard** [brianmhess/cassandra-loader#5]
Hi, 
We have  column value which has quoted data  , delimInQuotes

After the data loaded it has padded with extra “ 

so this has caused the incorrect data inserted was inappropriate to the other spark transform jobs.

we have data in CSV with 1,3,”{2.5,3.5,9, 2}”, 12345

after using useDelim=true   

output = 1,3,’”{2.5,3.5,9, 2}”’, 12345    with an extra ‘

Will you please look into it ?

Thanks
Santhi

**Comment by brianmhess** [comment]
This issue was due to not stripping the " on the input.  That has been fixed in v0.0.8.
