### ISSUE TITLE
Configurable memory settings for cassandra-loader.sh 

### ISSUE THREAD

**Issue by ajermakovics** [brianmhess/cassandra-loader#53]
Hi!

Noticed that the default [cassandra-loader.sh](https://github.com/brianmhess/cassandra-loader/blob/master/src/make/cassandra-loader.sh) script runs with 8G memory settings. Perhaps it is worth making this configurable? In some cases we're using cassandra loader on small virtual machines with few gb of memory.

As a workaround we're currently running cassandra-loader with `java -jar` and that way we can control the memory settings.

Thanks

**Comment by chaitu1124** [comment]
Hi, I am also facing memory issue. 

This is the Error Message, I was getting. 

# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 8589934592 bytes for committing reserved memory.

Let me know how you ran. What options you gave, I dont see any options for memory. 

Thanks,
Chaitanya

**Comment by ajermakovics** [comment]
@chaitu1124 You can run cassandra-loader standalone with `java -jar cassandra-loader -Xmx...`

**Comment by brianmhess** [comment]
I have lowered the default RAM to 1GB, but as @ajermakovics pointed out, cassandra-loader is also a jar, so you can run with java -Xmx... -jar cassandra-loader.
