### ISSUE TITLE
CSV file generated with ".0" on the end

### ISSUE THREAD

**Issue by adamdougal** [brianmhess/cassandra-loader#54]
When running the cassandra-unloader the csv file that gets generated is appended with `.0`.

E.g. when running this command:
```
cassandra-unloader -f output.csv -host host1 -schema "ks.table(a,b,c)"
```
a file called `output.csv.0` is created.

Is this intended behaviour as it looks like it is hard coded https://github.com/brianmhess/cassandra-loader/blob/master/src/main/java/com/datastax/loader/CqlDelimUnload.java#L364 ?

**Comment by kdp8791** [comment]
I believe this is intended. You're seeing ".0" because the default number of threads is 1, so only one file is being generated in the output. If you provide a numThreads, then you would see others like ".1", ".2", ".3", etc.

**Comment by adamdougal** [comment]
Ah okay, that makes sense and when digging a bit deeper through the code I can now see that!

Thanks!
