### ISSUE TITLE
separate directories for the files

### ISSUE THREAD

**Issue by santhikumard** [brianmhess/cassandra-loader#6]
is it also possible to add 3 directories  -input   -done  -failed  and push the input file to different directories after processing ?

**Comment by brianmhess** [comment]
I added a -successDir and a -failureDir.  If you set the -successDir, then if the file successfully loads, it will be moved to the success directory.  If you do not set it, then the file will remain in its original location.  Similarly, if you set the -failureDir, then if the file fails to load, it will be moved to the failure directory.

This is now in v0.0.9.
