### ISSUE TITLE
Misinterpreting UUID for String

### ISSUE THREAD

**Issue by zjoia** [brianmhess/cassandra-loader#60]
Loaded up V 0.22 today to continue large import. 
Got the following Error:
Invalid number in input number 0: For input string: ""42f6b987"
Error parsing line 2 in hackdatabase_xbox360iso.csv: "42f6b987-93b5-4878-9c9b-d0f0b9fa1447","6ffb7d56-f47b-4f9c-b871-47484f7f2efa","berkeratay@gmail.com","berkeratay","gmail.com","Bojeunx","88.247.173.143","","","","","","e41b6cfc6e4c374ead1c60d92e8aca17","vB","","","","","","","","","","","English","","","","","","","","","","","0"

Reverted back to V0.21 and issue is removed, I assume it has something to do with the "Fixed issue with quoted values (and in collections)" but I haven't look deep into it.

**Comment by brianmhess** [comment]
Can you share the DDL for the table and the command-line for loading?  I'd like to try to reproduce this.

**Comment by zjoia** [comment]
CREATE TABLE hdb.hack_record (
    id uuid,
    email text,
    emaildomain text,
    sourceid uuid,
    address text,
    aim text,
    birthday text,
    city text,
    country text,
    emailinbox text,
    facebook text,
    firstname text,
    hashtype text,
    ipaddress text,
    isremoved boolean,
    language text,
    lastip text,
    lastname text,
    middlename text,
    msn text,
    password text,
    passwordhash text,
    phonenumber text,
    politicalpartyregistration text,
    regdate timestamp,
    registrationip text,
    salt text,
    sex text,
    skype text,
    solr_query text,
    state text,
    timezone text,
    twitter text,
    username text,
    website text,
    yahoo text,
    zip text,
    PRIMARY KEY (id, email, emaildomain, sourceid)
) WITH CLUSTERING ORDER BY (email ASC, emaildomain ASC, sourceid ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';
CREATE CUSTOM INDEX hdb_hack_record_solr_query_index ON hdb.hack_record (solr_query) USING 'com.datastax.bdp.search.solr.Cql3SolrSecondaryIndex';


./cassandra-loader -host 10.240.0.9 -f import.csv -schema "hdb.hack_record(id,sourceId,email,emailInbox,emailDomain,username,ipAddress,phoneNumber,firstName,lastname,middleName,password,passwordHash,hashType,salt,address,city,state,zip,country,sex,birthday,website,regdate,language,timezone,aim,yahoo,msn,skype,twitter,facebook,registrationIP,lastIP,politicalPartyRegistration,isRemoved)" -user dude -pw XXXXX -skipRows 1 -boolStyle "1_0" -nullsUnset true -dateFormat 'YYY-MM-DD HH:mm:ss' -charsPerColumn "99999" -failureDir "../imported/fail/"

2 Records:
id,sourceId,email,emailInbox,emailDomain,username,ipAddress,phoneNumber,firstName,lastname,middleName,password,passwordHash,hashType,salt,address,city,state,zip,country,sex,birthday,website,regdate,language,timezone,aim,yahoo,msn,skype,twitter,facebook,registrationIP,lastIP,politicalPartyRegistration,isRemoved
"f282687c-485a-4f0c-b4c1-5ead13eddff7","d257a45c-ee87-429d-bf25-1c52c1382293","diyode@gmail.com","diyode","gmail.com","Diyo","88.163.79.189","","","","","","f95aaa0a0c2ae72a46094c506df5a5f2752b37a7","SHA-1","","","","","","","","1979-06-26","","","French","","","","","","","","","","","0"
"62d2ff54-9be0-43d3-a3d8-97d690a8fb46","d257a45c-ee87-429d-bf25-1c52c1382293","quepedo-chicas27@hotmail.com","quepedo-chicas27","hotmail.com","gimbo","83.77.48.4","","","","","","2308499ec4107701f5818da3893cebc74053d7f0","SHA-1","","","","","","","","","","","French","","","","","","","","","","","0"

**Comment by brianmhess** [comment]
Got it - yep, I had some quoting "fun" with collections.... sorry 'bout that.  I've fixed in Master and will push 0.23 soon (waiting on one other quick one, I hope).

**Comment by brianmhess** [comment]
Pushed 0.23.  This should cover this case.
