### ISSUE TITLE
Issues installing and running

### ISSUE THREAD

**Issue by rgcooper53** [brianmhess/cassandra-loader#63]
Trying to install and run for the first time.  Building from source, gradle fails with a series of access errors, unable to retrieve various components from repo1.maven.org and other sites, even though curl has no issue getting same objects.  I then copied the prebuilt version but it is probably not compatible with my RHEL7 installation on a VM - it complains about a version compatiblity issue -- Exception in thread "main" java.lang.UnsupportedClassVersionError: com/datastax/loader/CqlDelimLoad : Unsupported major.minor version 52.0.

Please advise, and thanks in advance.

**Comment by brianmhess** [comment]
The latter issue is usually an incompatibility with the version of Java that it was built with and the version of Java that you have installed.  I build with "1.8.0_66".  What version do you have installed?

As for the gradle/maven issues, it is a little hard to know without the actual settings, but I would do the following:
- check that your settings in ~/.m2 are correct
- check that the responses via curl are actually artifacts and not just error pages
- wipe out your Maven cache and try again: rm -rf ~/.m2/repository/
