### ISSUE TITLE
CQL schema strings longer than 4096 fail to parse

### ISSUE THREAD

**Issue by alfredo-gimenez** [brianmhess/cassandra-loader#65]
Because the cqlSchema is parsed using the csv parser, the size of schemaString is restricted to 4096 characters.

**Comment by jbax** [comment]
Hi there the parser is not restricted to 4096 characters, this is just the default limit. You can increase it or simply set the limit to `-1` to not have a limit at all.

As per [javadoc](https://github.com/uniVocity/univocity-parsers/blob/master/src/main/java/com/univocity/parsers/common/CommonSettings.java#L128), all you need to do is to use:

`settings.setMaxCharsPerColumn(-1);`and be done with it.

Hope this helps.

**Comment by brianmhess** [comment]
Fixed in v0.0.26

**Comment by alfredo-gimenez** [comment]
Great! The other issue I didn't mention in #65 was when you have parentheses in your table names. PR #66 fixes both problems.
