### ISSUE TITLE
[question] cassandra-loader vs sstableloader

### ISSUE THREAD

**Issue by balta2ar** [brianmhess/cassandra-loader#76]
Hello. Sorry in advance if I missed this explanation in the README.

Say, I have lots of data to put into Cassandra 2.1.x regularly. In terms of raw speed, what's the preferred tool to use: this one or sstableloader (as explained here https://www.datastax.com/dev/blog/using-the-cassandra-bulk-loader-updated)?

This tool is probably easier to use because sstableloader requires some additional Java code to write to prepare an sstable. But ignoring this factor and leaving only performance on the table, what's your suggestion? 

Thanks.

**Comment by brianmhess** [comment]
If your data is in delimited format (or JSON) then this tool is easier and faster.  If your data is in SSTable format (as in from a backup or another C* cluster) then sstableloader is better.
