### ISSUE TITLE
cassandra-loader -com.univocity.parsers.common.TextParsingException

### ISSUE THREAD

**Issue by risrikanth** [brianmhess/cassandra-loader#80]
Hi Team,

I have created csv file using cassandra-unloader and try to load this csv file data into cassandra table using cassander-loader iam getting below error. Could some help to resolve this issue.

Caused by: com.univocity.parsers.common.TextParsingException: Length of parsed input (4097) exceeds the maximum number of characters defined in your parser settings (4096).
Hint: Number of characters processed may have exceeded limit of 4096 characters per column. Use settings.setMaxCharsPerColumn(int) to define the maximum number of characters a column can have
Ensure your configuration is correct, with delimiters, quotes and escape sequences that match the input format you are trying to parse
Parser Configuration: CsvParserSettings:
        Auto configuration enabled=true
        Autodetect column delimiter=false
        Autodetect quotes=false
        Column reordering enabled=true
        Empty value=null
        Escape unquoted values=false
        Header extraction enabled=null
        Headers=null
        Ignore leading whitespaces=true
        Ignore trailing whitespaces=true
        Input buffer size=1048576
        Input reading on separate thread=true
        Keep escape sequences=true
        Keep quotes=true
        Length of content displayed on error=-1
        Line separator detection enabled=false
        Maximum number of characters per column=4096
        Maximum number of columns=512
        Normalize escaped line separators=true
        Null value=null
        Number of records to read=all
        Processor=none
        Restricting data in exceptions=false
        RowProcessor error handler=null
        Selected fields=none
        Skip empty lines=true
        Unescaped quote handling=nullFormat configuration:
        CsvFormat:
                Comment character=\0
                Field delimiter=,
                Line separator (normalized)=\n
                Line separator sequence=\n
                Quote character="
                Quote escape character=\
                Quote escape escape character=\

Thanks,
Srikanth.

**Comment by brianmhess** [comment]
You can set this via the -charsPerColumn, such as `-charsPerColumn 8192`.
