### ISSUE TITLE
unloader/loader issue

### ISSUE THREAD

**Issue by wavelet123** [brianmhess/cassandra-loader#81]
Hi,

We are experiencing the following issue.Could you please take a look?

Caused by: com.univocity.parsers.common.TextParsingException: Length of parsed input (4097) exceeds the maximum number of characters defined in your parser settings (4096). 
Hint: Number of characters processed may have exceeded limit of 4096 characters per column. Use settings.setMaxCharsPerColumn(int) to define the maximum number of characters a column can have
Ensure your configuration is correct, with delimiters, quotes and escape sequences that match the input format you are trying to parse
Parser Configuration: CsvParserSettings:

Thanks.

**Comment by brianmhess** [comment]
This can be configured with the `-charsPerColumn` option, such as `-charsPerColumn 8192`.
