### ISSUE TITLE
Timestamp nanosecond support

### ISSUE THREAD

**Issue by kyanovsky** [brianmhess/cassandra-loader#83]
Any chance of switching away from SimpleDateFormat? [DataTimeFormatter ](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#predefined)would support more precision.

**Comment by brianmhess** [comment]
Timestamps are only millisecond precision in C*
See: https://docs.datastax.com/en/cql/3.3/cql/cql_reference/timestamp_type_r.html
