### ISSUE TITLE
gradle loader doesn't work by me! 

### ISSUE THREAD

**Issue by WisDro** [brianmhess/cassandra-loader#97]
Hi all, 

I am a computer science student writing my bachelor thesis, and I have to test Cassandra DB, but I can't get on alone with importing data from a csv file and hope that I could get help here. 

I downloaded the :
https://github.com/brianmhess/cassandra-loader/releases/download/v0.0.27/cassandra-loader 
and I try to get along with the building, but I can't , someone can tell me what is meant with this sentence: 
To build this repository, simply clone this repo and run:
gradle loader

I hope someone can help me, because I'm hopeless right now. 

I just downloaded gradle and try to run the command gradle loader but I get this: 

![gradle](https://user-images.githubusercontent.com/18458575/42576907-f88bba12-8512-11e8-82c9-133daaecc76d.PNG)

@brianmhess  @jeromatron  PLEASE !!

**Comment by brianmhess** [comment]
If you just want to load data and do not want to modify the source code, then you can just download the file you did (https://github.com/brianmhess/cassandra-loader/releases/download/v0.0.27/cassandra-loader), chmod 777 that `cassandra-loader` file, and then just run it:
`./cassandra-loader -host 127.0.0.1 -f test.csv -schema "myks.mytbl(pkey,x)"`

If you want to modify the source, then clone this repository, make changes (if necessary) and use `gradle loader` to build.  The executable (`cassandra-loader`) will be in the `build/` subdirectory.

**Comment by WisDro** [comment]
do u have an Idee hwo to chmod 777 unter Windows ?

**Comment by brianmhess** [comment]
Ah - if you are running on Windows, then I do not believe you can just execute `cassandra-loader`.  Instead, you would run it with `java -jar cassandra-loader <arguments>` from the directory that the `cassandra-loader` file is in.

**Comment by WisDro** [comment]
and ja i just want to Import Data into Cassandra! and i know that chmod 777 just to change the access privileges, i've done now, but i still cann't run the command, should i run it under cqlsh? or in the Terminal by the cassandra_loader Directory? 

sorry but i Need it as quickly as possible. thank u

**Comment by brianmhess** [comment]
Are you running this command from Windows or Linux?
In either case, the `java -jar cassandra-loader <arguments>` approach will work.  You do _not_ run it via cqlsh.  It is a stand-alone executable.

**Comment by WisDro** [comment]
ok thank u, i will try it :)

**Comment by WisDro** [comment]
![unbenannt1](https://user-images.githubusercontent.com/18458575/42590327-0f6e60fc-8533-11e8-8bae-6948b70fd64f.PNG)

do u mean so ? 

or can u see where i'm doing wrong ?

**Comment by WisDro** [comment]
or can u see where my failure ?

**Comment by brianmhess** [comment]
I think that you want:
`java -jar cassandra-loader -host 127.0.0.1 -f M3000DB_L.csv -schema "test_m3000.ac_asd(acs_alarmid,acs_type,acs_State,acs_alarmtag,acs_dcs,acs_alarmtext,acs_flag,acs_staterg,acs_timestamp_Local)"`

**Comment by WisDro** [comment]
do u knwo how to solve this Problem ? "Unparseable date : "2017-05-31 14:54:40.530" , there is an Option withe dateFormat, but would that work for me, and how schould i write the Format for my dateFormat ?

**Comment by WisDro** [comment]
i did it so:  -dateformat " yyyy-mm-dd hh:mm:ss" , but so i lose the part of miliseconds, can i avoide that ?

**Comment by brianmhess** [comment]
Yep.  Read about the `-dateFormat` option here: https://github.com/brianmhess/cassandra-loader
